### ISSUE TITLE
Transmit creates junk (Flipper sees it as RAW) for NEC protocol

### ISSUE THREAD

**Issue by supaplextor** [IRMP-org/IRMP#88]
### Board
* [x] Other - please specify - M5StickC esp32

### IDE
* [x] Arduino IDE

### IR-Protocol
* [x] NEC

### Example to reproduce the issue
* [x] ReceiveAndSend

### Version
* [x] Yes I use the [latest repo version](https://github.com/Arduino-IRremote/Arduino-IRremote/archive/master.zip) and verified this!

### Pin(s) used for IR-receive, if not default
<code><pre>#define IRMP_INPUT_PIN   33
#define IRSND_OUTPUT_PIN 9</pre></code>

M5StickC has an I/R pair attached but I'm using the onboard IR for transmit.

### Current behavior

<code>https://gist.github.com/supaplextor/84deec2fc697b87f4ae17be48bb56dca</code>

When I use button A or B to transmit, FlipperZero sees the IR as raw not NEC like the OEM remote uses.

**checklist:**
- [x] I have **read** the README.md file thoroughly.
- [x] I have searched existing issues to see if there is anything I have missed.
- [x] I have browsed the examples for one, that matches my use case.
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [x] The title of the issue is helpful and relevant.
- [?] I checked, if at least one of the examples was working.

** We will start to close or delete issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

**Comment by plueschpruem** [comment]
I seem to have the same problem.
With the SAMSG32 protocol on an M5 Cardputer.
Input (on G1) works fine – I then take that and send it out on button press.
I can see the IR LED (on G44) blink with my phone camera, but the TV I use for testing won't notice it.
Using TONE doesn't seem to work, I commented out TONE_LEDC_CHANNEL and TONE_PIN.

I suspect the ESP32-S3 needing some special love, I already had to change my Serial.print() statements to USBSerial.print(). Maybe some timer settings have changed.
