### ISSUE TITLE
boot loop on Wemos Lolin S3 Mini

### ISSUE THREAD

**Issue by sartyx** [IRMP-org/IRMP#90]
### Board
* [x] ESP32 board
* [x] Other - please specify

ESP32 Wemos Lolin S3 Mini

### IDE
* [x] Arduino IDE

### IR-Protocol
* [x] Unknown

### Example to reproduce the issue
* [x] SimpleReceiver

### Version
3.6.2

Please delete all unchecked lines above :-)

### Pin(s) used for IR-receive, if not default
tried 5,6,8

### Current behavior

boot loop (same/similar for IRremote fork):

```
17:20:39.805 -> START C:\Users\A1\OneDrive\Dokumente\Arduino\IRMP_TinyReceiver\IRMP_TinyReceiver.ino from Feb 26 2024
17:20:39.805 -> Using library version 1.2.0
17:20:39.805 -> Ready to receive NEC IR signals at pin 6
17:20:40.739 -> 
17:20:40.739 -> abort() was called at PC 0x40378ec7 on core 1
17:20:40.739 -> 
17:20:40.739 -> 
17:20:40.739 -> Backtrace: 0x40377ace:0x3fc93980 0x4037b2fd:0x3fc939a0 0x40380b11:0x3fc939c0 0x40378ec7:0x3fc93a40 0x40378fd9:0x3fc93a70 0x403790a8:0x3fc93a90 0x42016f5e:0x3fc93ac0 0x42019f85:0x3fc93dd0 0x42021ebd:0x3fc93e00 0x4200cfc2:0x3fc93e30 0x4200d057:0x3fc93e60 0x42003a71:0x3fc93ee0 0x42003b66:0x3fc93f10 0x42001d59:0x3fc93f80 0x42001adf:0x3fc93fe0 0x42001873:0x3fc94070 0x40375311:0x3fc94090 0x42020539:0x3fc940b0 0x40375499:0x3fc940d0 0x403754be:0x3fc940f0 0x40378c35:0x3fc94110 0x42002716:0x3fcebda0
17:20:40.739 -> 
17:20:40.739 -> 
17:20:40.739 -> 
17:20:40.739 -> 
17:20:40.739 -> ELF file SHA256: 5dea38e6437604c2
17:20:40.739 -> 
17:20:40.739 -> Rebooting...
17:20:40.739 -> ESP-ROM:esp32s3-20210327
17:20:40.739 -> Build:Mar 27 2021
17:20:40.739 -> rst:0xc (RTC_SW_CPU_RST),boot:0x2b (SPI_FAST_FLASH_BOOT)
17:20:40.739 -> Saved PC:0x42020b8a
17:20:40.739 -> SPIWP:0xee
17:20:40.739 -> mode:DIO, clock div:1
17:20:40.739 -> load:0x3fce3808,len:0x44c
17:20:40.739 -> load:0x403c9700,len:0xbd8
17:20:40.739 -> load:0x403cc700,len:0x2a80
17:20:40.739 -> entry 0x403c98d0
17:20:41.019 -> 
```

**checklist:**
- [x] I have **read** the README.md file thoroughly.
- [x] I have searched existing issues to see if there is anything I have missed.
- x[] I have browsed the examples for one, that matches my use case.
- [x] Any code referenced is provided and if over 30 lines a gist is linked INSTEAD of it being pasted in here.
- [x] The title of the issue is helpful and relevant.
- [x] I checked, if at least one of the examples was working.
Yes simplereceiver is actually the same as in IRremote so both cause this behaviour 

** We will start to close or delete issues that do not follow these guidelines as it doesn't help the contributors who spend time trying to solve issues if the community ignores guidelines!**

**Comment by ArminJo** [comment]
Fixed
